name: build-arm64

on:
  workflow_dispatch:

jobs:
  build-windows-arm64:
    # Use native Windows ARM64 runner
    runs-on: windows-11-arm64
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          base-devel
          git
          mingw-w64-aarch64-gcc
          make
          libtool
          autoconf
          automake-wrapper
          mingw-w64-aarch64-libzip
          mingw-w64-aarch64-github-cli
          
    - uses: actions/checkout@v4
    
    - name: Prepare environment
      run: |
        git config --global core.autocrlf false
        
    - name: Build projects
      run: |
        repos=("libplist" "libimobiledevice-glue" "libusbmuxd" "libtatsu" "libimobiledevice" "libideviceactivation" "ideviceinstaller" "libirecovery" "idevicerestore")
        for repo in "${repos[@]}"; do
            echo "Building $repo..."
            git clone --depth=1 --recursive "https://github.com/libimobiledevice/$repo"
            pushd "$repo" > /dev/null
            ./autogen.sh --enable-debug --without-cython
            make -j install
            popd > /dev/null
        done
    
    - name: Prepare release
      run: |
        mkdir -p rel
        find /mingw64/bin/ -type f \( -name "*idevice*" -o \
                                      -name "*irecovery*" -o \
                                      -name "libimobiledevice*" -o \
                                      -name "libplist*" -o \
                                      -name "plistutil.exe" -o \
                                      -name "libusbmuxd*" -o \
                                      -name "inetcat.exe" -o \
                                      -name "iproxy.exe" -o \
                                      -name "libcurl*.dll" -o \
                                      -name "libtatsu*.dll" -o \
                                      -name "libxml2*.dll" -o \
                                      -name "libzip*.dll" -o \
                                      -name "zlib*.dll" -o \
                                      -name "libreadline*.dll" -o \
                                      -name "libbrotli*.dll" -o \
                                      -name "libiconv*.dll" -o \
                                      -name "libunistring*.dll" -o \
                                      -name "libssh*.dll" -o \
                                      -name "libintl*.dll" -o \
                                      -name "libidn*.dll" -o \
                                      -name "libnghttp*.dll" -o \
                                      -name "libpsl*.dll" -o \
                                      -name "libbz2*.dll" -o \
                                      -name "liblzma*.dll" -o \
                                      -name "libzstd*.dll" -o \
                                      -name "libtermcap*.dll" -o \
                                      -name "libcrypto*.dll" -o \
                                      -name "libssl*.dll" \) \
                                      -exec cp -v {} rel \;
        tar -C rel -cJvf libimobile-suite-latest_aarch64-mingw64.tar.xz .
    
    - name: Publish release
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        gh release create "${GITHUB_REF##*/}-${GITHUB_SHA:0:7}" --title "libimobiledevice ARM64 Release" libimobile-suite-latest_aarch64-mingw64.tar.xz
